services:
  app-pr-reviewer-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app-pr-reviewer-service
    ports:
      - "${SERVERS_REST_PORT:-8080}:${SERVERS_REST_PORT:-8080}"
    env_file:
      - .env
    environment:
      STORAGES_POSTGRES_HOST: db
    networks:
      - bridge_app
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped

  db:
    image: postgres:17.5
    shm_size: 128mb
    volumes:
      - ./backup:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${STORAGES_POSTGRES_USER}
      - POSTGRES_PASSWORD=${STORAGES_POSTGRES_PASS}
      - POSTGRES_DB=${STORAGES_POSTGRES_NAME}
      - POSTGRES_PORT=${STORAGES_POSTGRES_PORT}
    ports:
      - "${STORAGES_POSTGRES_PORT:-5432}:5432"
    networks:
      - bridge_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${STORAGES_POSTGRES_USER} -d ${STORAGES_POSTGRES_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations/sql",
        "-database", "postgres://${STORAGES_POSTGRES_USER}:${STORAGES_POSTGRES_PASS}@db:5432/${STORAGES_POSTGRES_NAME}?sslmode=${STORAGES_POSTGRES_SSLM}",
        "up"
      ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bridge_app
    env_file:
      - .env
    restart: "no"

networks:
  bridge_app:
    driver: bridge
